version: '2'

services:
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    extra_hosts:
      - "zookeeper0:10.100.194.215"
      - "zookeeper1:10.100.194.216"
      - "kafka0:10.100.194.215"
      - "kafka1:10.100.194.216"
      - "kafka2:10.100.194.214"
