server:
  port: 7900

spring:

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://10.100.194.211:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
