web.ribbon:
  ribbon:
    listOfServers : localhost:8002   #这里只使用一台ribbon服务器

ribbon:
  eureka:
    enabled: false  #禁止掉eureka功能

spring:
  application:
    name: client.feigh

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    healthcheck:
      enabled: true
logging:
  level:
    com.example.demo.feign.MyFeign1: DEBUG