
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#spring:
#  application:
#    name: webclient


webserver:
  ribbon:
    listOfServers : localhost:8002
    #NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule

ribbon:
  eureka:
    enabled: false